spring:
  datasource:
    username: root
    password: 123Moppo!@#
    url: jdbc:mysql://192.168.1.5:3306/lopdeals?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useTimezone=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 11151
  servlet:
    context-path: "/springcloud/timer"

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml #xml文件扫描
  type-aliases-package: own.auth.entity.po #包扫描路径,可以在xml文件中resultType="" 省略包路径名直接写pojo的类名
  configuration:
    map-underscore-to-camel-case: true #配置数据库字段下划线转java的驼峰, 避免(select user_id as userId) sql中写 as

logging:
  config: classpath:logback.xml #logback 日志继承, springboot默认是 slf4j+logback, 不需要引入依赖只需要 xml 配置文件即可